version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"