version: "3.8"

services:
  server:
    image: chessforandroid
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5566:5566/tcp
      - 5567:5567/tcp
    restart: unless-stopped
