version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - 5566:5566/tcp
      - 5567:5567/tcp
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=chessforandroid
      - MYSQL_USER=root
      - MYSQL_PASSWORD=putero

  db:
    image: mysql:8.0
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_DATABASE=chessforandroid
      - MYSQL_ROOT_PASSWORD=putero
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql/:/docker-entrypoint-initdb.d/:ro

volumes:
  mysql_data: {}