version: '3.8'

services:
  server:
    image: ghcr.io/chemecador/chessserver:{VERSION}
    environment:
      - MYSQL_HOST=
      - MYSQL_DB=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - 5566:5566/tcp
      - 5567:5567/tcp
    networks:
      - db_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s

networks:
  db_network:
    external: true